---
# tasks file for logrotate - EL Family

- name: EL Family | Installing {{ logrotate_app }}
  ansible.builtin.yum:
    name: "{{ logrotate_app }}"
    state: "{{ logrotate_desired_state }}"
    update_cache: yes

- name: "Setup logrotate configuration if defined"
  ansible.builtin.template:
    src: "{{ logrotate_template }}"
    dest: "{{ logrotate_config_dir }}/{{ item.name }}"
    mode: '0644'
  with_items: "{{ logrotate_configs }}"
  when: logrotate_configs is defined
